### ISSUE TITLE
TermDocumentMatrix() breaks with current walk-through code due to change in how TM handles tolower

### ISSUE THREAD

**Issue by DanielFletcher1** [chenmiao/Big_Data_Analytics_Web_Text#1]
@chenmiao 

First of all, thanks so much for this walk-through, I'm really enjoying it!

I ran through the code fine, until I got to this piece:  `tdm <- TermDocumentMatrix (sci.electr.train.p)`, which threw this `Error: inherits(doc, "TextDocument") is not TRUE`

Per this stackoverflow article answer (http://stackoverflow.com/questions/24191728/documenttermmatrix-error-on-corpus-argument), changes in `tm 0.6.0` from `tm 0.5.10` cause the `tolower` input to not necessarily return TextDocuments.

Applying the stackoverflow answer, I used `sci.electr.train.p <- tm_map (sci.electr.train, content_transformer(tolower))` instead of `sci.electr.train.p <- tm_map (sci.electr.train, tolower)` and was able to run `tdm <- TermDocumentMatrix (sci.electr.train.p)` without any errors.

I hope this helps.  Thanks, again.

**Comment by chenmiao** [comment]
Hi Daniel,

Thanks a lot for pointing out this issue. I've updated the page to reflect your suggestion. The R libraries update so quickly and it's so easy to get off the track :)

Thank you!

Miao

**Comment by DanielFletcher1** [comment]
I definitely hear you on the update frequency.  Also, I think I spotted one or two more issues down the page.  However, I was unsure if there was something wrong on my end, and I failed to do a root-cause analysis, so you might consider running the scripts to check.

You're very welcome.

**Comment by chenmiao** [comment]
Thanks for pointing that out - I need to do a walk through of the code and update them (or work on a new one for the newer TM package)! thanks.

**Comment by lkarisa** [comment]
thanks. it has worked very well for me.
